
services:
  school-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-api-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT= "Production"
      - ASPNETCORE_URLS= "http://+:8080"
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    
    env_file:
      - .env
    restart: unless-stopped